# Global settings applied to the whole site.
# “command” is your build command.
# “publish” is the directory to publish (relative to root of your repo).

[build]
  command = "npm run prerender"
  publish = "buildPrerendered"

[[headers]]
for = "/*"
  [headers.values]
  Content-Security-Policy = "script-src 'self' https://api.scrivito.com https://app.intercom.io https://assets.scrivito.com https://js.intercomcdn.com https://widget.intercom.io https://www.google-analytics.com https://sc.lfeeder.com/lftracker_v1_ https://*.lfeeder.com https://*.leadfeeder.com https://cdn.leadinfo.net/ping.js https://client.crisp.chat;"
