import * as Scrivito from "scrivito";

const BidEntrepeneursWidget = Scrivito.provideWidgetClass("BidEntrepeneursWidget", {
  attributes: {
    assist: ["reference", {only: "Image"}],
    topTitle: "string",
    topLink: "link",
    circleTitle: "string",
    circleHeadline1: "string",
    circleHeadline2: "string",
    circleHeadline3: "string",
    circleHeadline4: "string",
    circleText1: "string",
    circleText2: "string",
    circleText3: "string",
    circleText4: "string",
    circleNumber1: "string",
    circleNumber2: "string",
    circleNumber3: "string",
    circleNumber4: "string",
    statsNumber: "string",
    statsText: "string",
    statsNumber2: "string",
    statsText2: "string",
    statsNumber3: "string",
    statsText3: "string",
    quote: "string",
    name: "string",
    position: "string",
    quote2: "string",
    name2: "string",
    position2: "string",
    info1: ["reference", {only: "Image"}],
    info2: ["reference", {only: "Image"}],
    info3: ["reference", {only: "Image"}],
    strategyText1: "html",
    strategyText2: "html",
    strategyText3: "html",
    strategyText4: "html",
    strategyText5: "html",
    strategyText6: "html",
    strategyImage1: ["reference", {only: "Image"}],
    strategyImage2: ["reference", {only: "Image"}],
    strategyImage3: ["reference", {only: "Image"}],
    strategyImage4: ["reference", {only: "Image"}],
    strategyImage5: ["reference", {only: "Image"}],
    strategyImage6: ["reference", {only: "Image"}],
    strategyDescription: "string",
    strategyLink: "link",
    leverTitle: "string",
    company1: "string",
    company2: "string",
    company3: "string",
    company4: "string",
    company5: "string",
    company6: "string",
    companyEntry: "string",
    companyExit: "string",
    lever1Title: "string",
    lever2Title: "string",
    lever3Title: "string",
    lever4Title: "string",
    lever5Title: "string",
    lever6Title: "string",
    lever1Text: "string",
    lever2Text: "string",
    lever3Text: "string",
    lever4Text: "string",
    lever5Text: "string",
    lever6Text: "string",
    lever1Tooltip: "string",
    lever2Tooltip: "string",
    lever3Tooltip: "string",
    lever4Tooltip: "string",
    lever5Tooltip: "string",
    lever6Tooltip: "string",
    growth1:  "html",
    growth2:  "html",
    growth3:  "html",
    growth4:  "html",
    growth5:  "html",
    growth6:  "html",
    infoTitle1: "string",
    infoLink1: "link",
    infoTitle2: "string",
    infoLink2: "link",
    infoTitle3: "string",
    infoLink3: "link",
    networkTitle: "string",
    partnerTitle: "string",
    partner: "widgetlist",
    slider: "widgetlist",
    helpTitle:  "string",
    tagSection: "widgetlist",
    link: "link"
  },
  
});

export default BidEntrepeneursWidget;
