import * as Scrivito from "scrivito";

const BidAboutWidget = Scrivito.provideWidgetClass("BidAboutWidget", {
  attributes: {
    content: "widgetlist",
    fact1: "string",
    fact2: "string",
    fact3: "string",
    fact4: "string",
    fact1Text: "string",
    fact2Text: "string",
    fact3Text: "string",
    fact4Text: "string",
    teamImage: ["reference", { only: "Image" }],
    testimonialsBg: ["reference", { only: "Image" }],
    teamLink1: "link",
    teamLink2: "link",
    aboutIntro1: "html",
    aboutIntro2: "html",
    aboutButton: "link",
    quote: "string",
    name: "string",
    position: "string",
    bodyBottom: "widgetlist",
    navNext: "string",
    nextMember: "string",
    job: "string",
    aboutTitle: "string",
    aboutText: "string",
    aboutDescription: "string",
    triggerName1: "string",
    triggerText1: "string",
    triggerName2: "string",
    triggerText2: "string",
    triggerName3: "string",
    triggerText3: "string",
    sectionTitle: "string",
    serviceItemName1: "string",
    serviceItemText1: "string",
    serviceItemName2: "string",
    serviceItemText2: "string",
    serviceItemName3: "string",
    serviceItemText3: "string",
    serviceItemName4: "string",
    serviceItemText4: "string",
    serviceItemName5: "string",
    serviceItemText5: "string",
    serviceItemName6: "string",
    serviceItemText6: "string",
    allServicesLink: "link",
    teamSectionTitle: "string",
    fullTeam: "link",
  },
  
});

export default BidAboutWidget;
