import * as Scrivito from "scrivito";

Scrivito.provideEditingConfig("BidAboutWidget", {
  title: "Bid About",
  
  properties: [
    "headline",
    "fact1", 
    "fact1Text",
    "fact2",
    "fact2Text",
    "fact3",
    "fact3Text",
    "fact4",
    "fact4Text",
    "teamImage",
    "teamLink1",
    "teamLink2",
    "aboutIntro1",
    "aboutIntro2",
    "quote",
    "name",
    "position",
    "aboutButton",
    "aboutTitle",
    "aboutText",
    "aboutDescription",
    "bodyBottom",
    "triggerName1",
    "triggerText1",
    "triggerName2",
    "triggerText2",
    "triggerName3",
    "triggerText3",
    "sectionTitle",
    "serviceItemName1",
    "serviceItemText1",
    "serviceItemName2",
    "serviceItemText2",
    "serviceItemName3",
    "serviceItemText3",
    "allServicesLink",
  ],
  
});
